# Generated by Django 5.2.6 on 2026-09-08 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('sla_horas', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mesa_categorias',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('color_hex', models.CharField(max_length=7)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('es_final', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mesa_estados',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MesaRolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(unique=True)),
                ('rol', models.CharField(choices=[('solicitante', 'Solicitante'), ('tecnico', 'Técnico / Encargado'), ('admin', 'Administrador de mesa')], max_length=20)),
            ],
            options={
                'db_table': 'mesa_roles_usuario',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('email_contacto', models.CharField(blank=True, max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=100)),
                ('requerimiento', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.DO_NOTHING, to='users.area')),
                ('asignado_a', models.ForeignKey(blank=True, db_column='id_asignado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mesa_ayuda.categoria')),
                ('estado', models.ForeignKey(db_column='estado', default='borrador', on_delete=django.db.models.deletion.PROTECT, to='mesa_ayuda.estadosolicitud')),
                ('solicitante', models.ForeignKey(db_column='id_solicitante', on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mesa_solicitudes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_origen', models.CharField(blank=True, max_length=30)),
                ('estado_destino', models.CharField(max_length=30)),
                ('motivo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(db_column='id_actor', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='mesa_ayuda.solicitud')),
            ],
            options={
                'db_table': 'mesa_historial_estado',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField()),
                ('es_interno', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(db_column='id_autor', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='mesa_ayuda.solicitud')),
            ],
            options={
                'db_table': 'mesa_comentarios',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='solicitudes/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('tamano_bytes', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(db_column='id_subido_por', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos', to='mesa_ayuda.comentario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='mesa_ayuda.solicitud')),
            ],
            options={
                'db_table': 'mesa_adjuntos',
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('codigo', models.CharField(max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='mesa_ayuda.categoria')),
            ],
            options={
                'db_table': 'mesa_tipos_actividad',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('categoria', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mesa_ayuda.tipoactividad'),
        ),
    ]
