# Generated by Django 5.2.6 on 2026-09-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_ayuda', '0002_flujo_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='confirmado_solicitante_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sla_pausa_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sla_segundos_pausados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='requerimiento',
            field=models.TextField(blank=True, default=''),
        ),
    ]
