# Generated by Django 5.2.6 on 2026-09-08 18:07

import users.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_personal', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('movil_personal', models.CharField(blank=True, max_length=100, null=True)),
                ('movil_coorporativo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', users.fields.SafeDateField(blank=True, null=True)),
                ('fecha_ingreso', users.fields.SafeDateField(blank=True, null=True)),
                ('password', models.CharField(blank=True, db_column='contrasena', max_length=128, null=True)),
                ('documento', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=11, null=True)),
                ('genero', models.CharField(blank=True, max_length=1, null=True)),
                ('nro_cuenta', models.CharField(blank=True, max_length=100, null=True)),
                ('afp', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('correlativo', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id_banco', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bancos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_ingles', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('activo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cargos',
                'managed': False,
            },
        ),
    ]
